- THA-1/Solution/Pradhumn/index.html
> ✅ THA(1) done

- THA-1/Solution/Hardik/index.html
> ✅ Hardik : THA-1

- THA-1/Solution/Shushmita/index.html
> ✅ Shushmita: THA-1

- THA-1/Solution/Srujan/Letter.html
> Srujan-THA1

- THA-1/Solution/Nishant/index.html
> ✅ Nishant: THA-1 HTML

- THA-1/Solution/Praveen/index.html
> ✅ praveen-tha-1

- THA-2/Solution/Praveen/index.html
- THA-2/Solution/Praveen/style.css
> ✅ praveen-tha-2

- THA-1/Solution/Sakshi/index.html
> completed tha1

- THA-2/Solution/Hardik/index.css
- THA-2/Solution/Hardik/index.html
> ✅ Hardik : THA-2

- THA-1/Solution/Samir/index.html
> ✅ samir: tha1

- THA-2/Solution/Shushmita/css/style.css
- THA-2/Solution/Shushmita/index.html
> ✅ Shushmita: THA-2

- THA-1/Solution/Harsh/index.html
> ✅ Harsh-tha1

- THA-1/Solution/Rajdeep/THA_1.html
> ✅ THA-1 Done

- THA-2/Solution/Rajdeep/THA-2.html
- THA-2/Solution/Rajdeep/style.css
> ✅ Rajdeep-THA-2

- THA-2/Solution/Sanjay/index.html
- THA-2/Solution/Sanjay/style.css
> ✅  Sanjay: THA-2

- THA-3/Solution/Rajdeep/index.html
- THA-3/Solution/Rajdeep/style.css
> Rajdeep tha3

- THA-3/Solution/Shushmita/css/style.css
- THA-3/Solution/Shushmita/index.html
> ✅ Shushmita: THA-3

- .vscode/settings.json
- THA-3/Solution/Srujan/index.html
- THA-3/Solution/Srujan/style.css
> ✅ Srujan: THA-3

- THA-1/Solution/Devashish/index.html
> ✅ Devashish -THA-1 Done

- THA-3/Solution/Sanjay/index.html
- THA-3/Solution/Sanjay/style.css
> ✅ Sanjay: THA-3

- THA-4/Solution/Rajdeep/index.html
- THA-4/Solution/Rajdeep/style.css
> ✅Rajdeep_THA4

- THA-4/Solution/Shushmita/index.html
- THA-4/Solution/Shushmita/style.css
> ✅ Shushmita: THA-4

- THA-6/Solution/Samir/index.js
> ✅ samir:THA-6

- THA-6/Solution/Srujan/index.js
> Srujan:THA6

- THA-3/Solution/Sakshi/index.html
- THA-3/Solution/Sakshi/style.css
> THA-3 done

- THA-4/Solution/Sakshi/index.html
- THA-4/Solution/Sakshi/style.css
> ✅ tha-4 done

- THA-5/Solution/Sakshi/index.html
- THA-5/Solution/Sakshi/style.css
> ✅ Sakshi:tha-5

- THA-7/Solution/Samir/index.js
> ✅ samir:THA-7

- THA-6/Solution/Shushmita/index.js
> ✅ Shushmita: THA-6

- THA-7/Solution/Srujan/index.js
> Srujan:THA7

- THA-5/Solution/Sanjay/index.html
- THA-5/Solution/Sanjay/index.js
- THA-5/Solution/Sanjay/style.css
> ✅ Sanjay: THA-5

- THA-5/Solution/Rajdeep/index.html
- THA-5/Solution/Rajdeep/script.js
- THA-5/Solution/Rajdeep/style.css
> Rajdeep THa-5

- THA-2/Solution/Nishant/index.html
> ✅ Nishant: THA-2 (title updated)

- THA-6/Solution/Sakshi/index.js
> ✅ Sakshi: THA-6

- THA-8/Solution/Srujan/index.html
- THA-8/Solution/Srujan/script.js
- THA-8/Solution/Srujan/style.css
> Srujan:THA-8

- THA-7/Solution/Sakshi/index.js
> ✅ Sakshi: THA-7

- THA-10/Solution/Sanjay/index.html
- THA-10/Solution/Sanjay/index.js
- THA-10/Solution/Sanjay/style.css
> ✅ sanjay-tha-10

- THA-8/Solution/Sanjay/index.html
- THA-8/Solution/Sanjay/index.js
- THA-8/Solution/Sanjay/style.css
> ✅ Sanjay-THA-8

- THA-9/Solution/Sanjay/index.html
- THA-9/Solution/Sanjay/index.js
- THA-9/Solution/Sanjay/style.css
Pixel Board with Numerical Stats.
> ✅ sanjay-tha-9

- THA-7/Solution/Shushmita/index.js
- THA-7/Solution/Shushmita/questions.txt
> ✅ Shushmita: THA-7

- THA-11/Solution/Srujan/index.html
- THA-11/Solution/Srujan/script.js
- THA-11/Solution/Srujan/style.css
> Srujan:THA11

- THA-6/Solution/Rajdeep/script.js
> THA-6 Done

- THA-7/Solution/Rajdeep/script.js
> THA-7 Done

- THA-13/Solution/Samir/index.html
- THA-13/Solution/Samir/script.js
- THA-13/Solution/Samir/style.css
> ✔samir:THA-13

- THA-13/Solution/Srujan/index.html
- THA-13/Solution/Srujan/script.js
- THA-13/Solution/Srujan/style.css
> Srujan:THA-13

- THA-13/Solution/Rajdeep/index.html
- THA-13/Solution/Rajdeep/script.js
- THA-13/Solution/Rajdeep/style.css
> ✅Rajdeep_THA-13

- THA-12/Solution/Srujan/index.html
- THA-12/Solution/Srujan/script.js
- THA-12/Solution/Srujan/style.css
> Srujan:THA-12

- THA-11/Solution/Rajdeep/index.html
- THA-11/Solution/Rajdeep/script.js
- THA-11/Solution/Rajdeep/style.css
> ✅Rajdeep_THA-11

- THA-16/Solution/Rajdeep/ChessBoard/.gitignore
- THA-16/Solution/Rajdeep/ChessBoard/README.md
- THA-16/Solution/Rajdeep/ChessBoard/package-lock.json
- THA-16/Solution/Rajdeep/ChessBoard/package.json
- THA-16/Solution/Rajdeep/ChessBoard/public/index.html
- THA-16/Solution/Rajdeep/ChessBoard/public/manifest.json
- THA-16/Solution/Rajdeep/ChessBoard/public/robots.txt
- THA-16/Solution/Rajdeep/ChessBoard/src/App.js
- THA-16/Solution/Rajdeep/ChessBoard/src/Components/box.js
- THA-16/Solution/Rajdeep/ChessBoard/src/Styles/App.css
- THA-16/Solution/Rajdeep/ChessBoard/src/Styles/box.css
- THA-16/Solution/Rajdeep/ChessBoard/src/index.js
- THA-16/Solution/Rajdeep/card/.gitignore
- THA-16/Solution/Rajdeep/card/README.md
- THA-16/Solution/Rajdeep/card/package-lock.json
- THA-16/Solution/Rajdeep/card/package.json
- THA-16/Solution/Rajdeep/card/public/index.html
- THA-16/Solution/Rajdeep/card/public/manifest.json
- THA-16/Solution/Rajdeep/card/public/robots.txt
- THA-16/Solution/Rajdeep/card/src/App.js
- THA-16/Solution/Rajdeep/card/src/Components/Card.js
- THA-16/Solution/Rajdeep/card/src/Styles/App.css
- THA-16/Solution/Rajdeep/card/src/Styles/card.css
- THA-16/Solution/Rajdeep/card/src/index.js
> ✅THA-16-Rajdeep

- THA-12/Solution/Rajdeep/index.html
- THA-12/Solution/Rajdeep/index.js
- THA-12/Solution/Rajdeep/style.css
> ✅THA-12_rajdeep

- THA-18/Solution/Rajdeep/.gitignore
- THA-18/Solution/Rajdeep/README.md
- THA-18/Solution/Rajdeep/package-lock.json
- THA-18/Solution/Rajdeep/package.json
- THA-18/Solution/Rajdeep/public/index.html
- THA-18/Solution/Rajdeep/public/manifest.json
- THA-18/Solution/Rajdeep/public/robots.txt
- THA-18/Solution/Rajdeep/src/App.js
- THA-18/Solution/Rajdeep/src/Components/box.js
- THA-18/Solution/Rajdeep/src/Styles/App.css
- THA-18/Solution/Rajdeep/src/Styles/box.css
- THA-18/Solution/Rajdeep/src/index.js
> ✅THA-18_rajdeep
